# See spec/architecture/firewall.md.

[[rules]]
name = "Pass Probe"
phase = "http_request_firewall_custom"
action = "skip"
skip_phases = ["http_ratelimit"]
expression = "../all/pass-probe.txt"

[[rules]]
name = "Block Probes"
phase = "http_request_firewall_custom"
action = "block"
expression = "../all/block-probes.txt"

[[rules]]
name = "Site Files Only"
phase = "http_request_firewall_custom"
action = "block"
expression = "site-files-only.txt"

[[rules]]
name = "Referral Redirect"
phase = "http_request_dynamic_redirect"
action = "redirect"
expression = "referral-redirect.txt"
target = 'wildcard_replace(http.request.full_uri, r"https://www.*/*", r"https://${1}/${2}?ref=www")'
status = 301

[[rules]]
name = "Subdomain Migration"
phase = "http_request_dynamic_redirect"
action = "redirect"
expression = "subdomain-migration.txt"
target = 'wildcard_replace(http.request.full_uri, "*://*.canmi.net/*", "https://${2}.canmi.app/${3}")'
preserve_query_string = true
status = 307

[[rules]]
name = "Rate Cap"
phase = "http_ratelimit"
action = "block"
expression = "rate-cap.txt"
characteristics = ["cf.colo.id", "ip.src"]
period = 10
requests_per_period = 150
mitigation_timeout = 10
