//! The record written for every asset.
//!
//! Two shapes come out of the same data and must never be produced separately. One file per
//! asset, `{blake3}.json`, published to R2 so the metadata API can answer a single lookup
//! without reading anything else. One merged file, committed, so the site build can inline
//! placeholders into articles without the images being present at all.
//!
//! Both are generated by one command in one pass. Nothing here is ever hand-edited: the
//! originals live outside git, so a manually corrected manifest would be a claim nothing can
//! check.

use super::{Derived, Variant};
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

/// Bumped when the shape changes, so a reader can tell rather than guess. The first change
/// without one is the one that corrupts silently: 1 the original shape; 2 assets gain a
/// `description`; 3 `description` moves to `data/record/media.yaml`, `preview` and `original` are
/// dropped, and camera data arrives as `metadata`; 4 `type` becomes a discriminant, so each kind
/// gets its own body. See spec/architecture/video/pipeline.md, "The record is one shape per kind,
/// not one shape with holes".
pub const VERSION: u32 = 4;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Document {
	pub version: u32,
	pub media: Media,
}

/// What every asset has, whatever it is made of.
///
/// The envelope carries identity and time; the body carries the kind. Splitting them is the
/// point of version 4: a video under the picture's shape has to put something in `thumbhash`,
/// and both the poster's hash and an empty string are untrue. Absent is the honest answer, and
/// only a per-kind body can give it -- which also makes asking a video for its thumbhash a
/// compile error rather than a field that reads empty.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Media {
	/// ISO 8601 in UTC. Not local time: a record that means a different instant depending on
	/// where it is read is not a record.
	pub created: String,
	pub updated: String,
	/// The original's content id, and the identity of the asset.
	pub blake3: String,
	/// Flattened, so `type` and the body's fields stay siblings at the top of the record
	/// exactly where they were before the split. That is what lets version 3 load unchanged.
	#[serde(flatten)]
	pub body: Body,
}

impl Media {
	/// The picture this record is, or nothing when it is not one.
	///
	/// Every caller that only makes sense for a picture goes through here, so the place a
	/// video is turned away is a visible line rather than an empty string further down.
	pub fn image(&self) -> Option<&Image> {
		match &self.body {
			Body::Image(image) => Some(image),
			Body::Video(_) => None,
		}
	}

	pub fn video(&self) -> Option<&Video> {
		match &self.body {
			Body::Video(video) => Some(video),
			Body::Image(_) => None,
		}
	}

	/// The same, to be written to. `cms captions` attaches a track to a clip already published,
	/// which is the one operation that changes a record without deriving anything.
	pub fn video_mut(&mut self) -> Option<&mut Video> {
		match &mut self.body {
			Body::Video(video) => Some(video),
			Body::Image(_) => None,
		}
	}

	/// What `type` says on disk, for a report that has to name the kind without matching on it.
	pub fn kind(&self) -> &'static str {
		match &self.body {
			Body::Image(_) => "image",
			Body::Video(_) => "video",
		}
	}
}

/// One shape per kind, tagged by the field that already named the kind.
///
/// Internally tagged rather than adjacent or external, because `type` was the first field of
/// every record written since version 1 and a discriminant that moves would make every one of
/// them unreadable for the sake of a serde default.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum Body {
	Image(Image),
	Video(Video),
}

/// A picture: exactly what version 3 held, minus the fields the envelope took.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Image {
	/// Base64 thumbhash: the compact canonical placeholder.
	///
	/// The only form kept. A decoded copy used to sit beside it, which was the same picture
	/// written twice -- the build can decode this once and inline the result, and a second
	/// stored form is a second thing to keep in step.
	pub thumbhash: String,
	pub source: Source,
	/// What the camera recorded, read from the original at import.
	///
	/// Absent when extraction never ran; present and empty when it ran and the file had
	/// nothing, which is what every screenshot answers. See the module in `image::exif` for
	/// why that distinction is carried by the container rather than by nulls.
	#[serde(default, skip_serializing_if = "Option::is_none")]
	pub metadata: Option<super::exif::Metadata>,
	/// Keyed by each variant's own content id, exactly as the asset is keyed by the
	/// original's. Every stored object is addressed the same way.
	pub variants: BTreeMap<String, VariantRecord>,
}

/// A clip: one codec, one container, and the numbers a player needs before it can start.
///
/// No thumbhash and no `metadata`. The placeholder a reader sees is the poster, which is an
/// ordinary image asset with its own record; there is no camera account of a cut excerpt to
/// keep. See spec/architecture/video/pipeline.md.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Video {
	pub source: VideoSource,
	/// Content id of the poster frame, which is an image asset in its own right rather than a
	/// field of this one. It is the fallback a device without a decoder is left with, so it has
	/// to be an `<img>` a browser paints with no script.
	pub poster: String,
	pub variants: BTreeMap<String, VideoVariant>,
	/// Keyed by each track's own content id, like everything else stored here. Empty is the
	/// common case and writes nothing.
	#[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
	pub captions: BTreeMap<String, Caption>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct VideoSource {
	pub mime: String,
	pub width: u32,
	pub height: u32,
	/// Reduced by the greatest common divisor, exactly as a picture's is.
	pub ratio: String,
	pub bytes: u64,
	/// Seconds.
	pub duration: f64,
	pub frame_rate: f64,
	/// The denominator of the progress bar the software-decode path shows. Without it that bar
	/// cannot be honest, which is the whole reason a frame count is stored at all.
	pub frames: u64,
	pub audio: bool,
	/// Integrated loudness (LUFS) and true peak (dBTP), from EBU R128. See
	/// spec/architecture/video/pipeline.md, "Loudness, not peak, sets the target", for the gain
	/// formula.
	///
	/// Absent for a clip with no audio, or one imported before this was measured -- optional
	/// rather than zero, since zero would read as the loudest possible clip.
	#[serde(default, skip_serializing_if = "Option::is_none")]
	pub loudness: Option<f64>,
	#[serde(default, skip_serializing_if = "Option::is_none")]
	pub peak: Option<f64>,
}

/// One rung of the ladder.
///
/// `quality` does not carry over from a picture: it is a 0..1 the image encoder was handed, and
/// a video's CRF is not the same quantity under another name. What a `<source>` element has to
/// be told is the full codec string, so that is what is kept instead.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct VideoVariant {
	pub mime: String,
	pub width: u32,
	pub height: u32,
	pub bytes: u64,
	/// The whole string, `av01.0.05M.08` rather than `av01`. A partial one tells a browser
	/// nothing it can decide on.
	pub codec: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Caption {
	pub mime: String,
	/// BCP 47, `en`.
	pub language: String,
	/// `captions`, `subtitles` or `descriptions`: what the `<track>` element is told.
	pub kind: String,
	pub bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Source {
	pub mime: String,
	pub width: u32,
	pub height: u32,
	/// Reduced by the greatest common divisor, so it is exact rather than snapped to a
	/// familiar name. Screenshots rarely land on a recognisable ratio.
	pub ratio: String,
	pub bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct VariantRecord {
	pub mime: String,
	pub width: u32,
	pub height: u32,
	/// Normalised 0..1, as a number so it can be compared without parsing.
	pub quality: f32,
	pub bytes: u64,
}

/// Every asset, merged. This is the file that gets committed.
///
/// One entry per asset, each the same shape as the document published beside the bytes, so a
/// reader that can parse one can parse the other. `created` is the day the file itself first
/// appeared and `updated` moves whenever anything in it does -- the same pair every record
/// here carries, at the level above them.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Merged {
	pub version: u32,
	#[serde(default)]
	pub created: String,
	#[serde(default)]
	pub updated: String,
	/// Accepts the old key so a manifest written before the rename still loads.
	#[serde(alias = "assets")]
	pub media: BTreeMap<String, Media>,
}

/// Bring a manifest read from disk up to the current shape and find stale per-asset records.
///
/// `#[serde(default)]` fields are already correct on load; only the version number needs a
/// bump. Staleness is per sidecar, not this aggregate version -- it can advance before a
/// guarded write finishes, which would hide staleness forever as a one-shot gate. Version 4
/// needs no transform: checked, not reasoned, per spec/architecture/media.md, "The manifest has
/// versions, and only one is current". Unreadable shapes get a branch here, never an alias.
pub fn migrate(merged: &mut Merged, metadata: &Path) -> Vec<String> {
	merged.version = merged.version.max(VERSION);
	merged
		.media
		.keys()
		.filter(|cid| {
			let path = super::store::meta_path(metadata, cid);
			std::fs::read_to_string(path)
				.ok()
				.and_then(|text| serde_json::from_str::<Document>(&text).ok())
				.is_none_or(|document| document.version < VERSION)
		})
		.cloned()
		.collect()
}

pub fn ratio_of(width: u32, height: u32) -> String {
	let divisor = gcd(width, height).max(1);
	format!("{}:{}", width / divisor, height / divisor)
}

fn gcd(a: u32, b: u32) -> u32 {
	if b == 0 { a } else { gcd(b, a % b) }
}

pub fn now() -> String {
	jiff::Timestamp::now().to_string()
}

fn record(variant: &Variant) -> VariantRecord {
	VariantRecord {
		mime: variant.format.mime().to_owned(),
		width: variant.width,
		height: variant.height,
		quality: variant.format.quality(),
		bytes: variant.bytes.len() as u64,
	}
}

/// Build the record for one asset. `created` is carried over when the asset was seen before,
/// so re-running does not rewrite the day it first appeared.
pub fn media_for(
	derived: &Derived,
	source_mime: &str,
	source_bytes: u64,
	created: Option<&str>,
	metadata: Option<super::exif::Metadata>,
) -> Media {
	let timestamp = now();
	Media {
		created: created.unwrap_or(&timestamp).to_owned(),
		updated: timestamp,
		blake3: derived.cid.clone(),
		body: Body::Image(Image {
			thumbhash: STANDARD.encode(&derived.thumb),
			source: Source {
				mime: source_mime.to_owned(),
				width: derived.width,
				height: derived.height,
				ratio: ratio_of(derived.width, derived.height),
				bytes: source_bytes,
			},
			metadata,
			variants: derived
				.variants
				.iter()
				.map(|variant| (variant.cid.clone(), record(variant)))
				.collect(),
		}),
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn reduces_a_ratio_exactly() {
		assert_eq!(ratio_of(1920, 1080), "16:9");
		assert_eq!(ratio_of(800, 600), "4:3");
		assert_eq!(ratio_of(500, 500), "1:1");
	}

	#[test]
	fn does_not_pretend_an_awkward_ratio_is_a_familiar_one() {
		// A screenshot is whatever the window was. Snapping this to 16:9 would be a lie that
		// an aspect-ratio box would then render wrong.
		assert_eq!(ratio_of(2356, 1204), "589:301");
	}

	#[test]
	fn survives_a_zero_dimension() {
		assert_eq!(ratio_of(0, 0), "0:0");
	}

	#[test]
	fn timestamps_are_iso_8601_in_utc() {
		let value = now();
		assert!(value.ends_with('Z'), "not UTC: {value}");
		assert!(value.contains('T'), "not ISO 8601: {value}");
	}

	#[test]
	fn a_document_round_trips_through_json() {
		let document = Document {
			version: VERSION,
			media: Media {
				created: "2026-07-30T13:14:52Z".into(),
				updated: "2026-07-30T13:14:52Z".into(),
				blake3: "44b6081deaf0242ca3bf83d62a3b6c95".into(),
				body: Body::Image(Image {
					thumbhash: "1QcSHQRnh493".into(),
					source: Source {
						mime: "image/png".into(),
						width: 2356,
						height: 1204,
						ratio: ratio_of(2356, 1204),
						bytes: 6_612_480,
					},
					metadata: None,
					variants: BTreeMap::new(),
				}),
			},
		};
		let text = serde_json::to_string(&document).expect("serialise");
		assert_eq!(serde_json::from_str::<Document>(&text).expect("deserialise"), document);
		// `type` is a keyword in Rust and a field name in the document; the rename has to
		// survive both directions, and it is now the discriminant rather than a label.
		assert!(text.contains("\"type\":\"image\""));
	}

	#[test]
	fn a_video_round_trips_through_json() {
		let document = Document {
			version: VERSION,
			media: Media {
				created: "2026-09-14T00:00:00Z".into(),
				updated: "2026-09-14T00:00:00Z".into(),
				blake3: "aa11bb22cc33dd44ee55ff6677889900".into(),
				body: Body::Video(Video {
					source: VideoSource {
						mime: "video/mp4".into(),
						width: 1920,
						height: 1080,
						ratio: ratio_of(1920, 1080),
						bytes: 4_112_384,
						duration: 25.5,
						frame_rate: 30.0,
						frames: 765,
						audio: true,
						loudness: None,
						peak: None,
					},
					poster: "bb22cc33dd44ee55ff66778899001122".into(),
					variants: BTreeMap::from([(
						"cc33dd44ee55ff667788990011223344".to_owned(),
						VideoVariant {
							mime: "video/mp4".into(),
							width: 1920,
							height: 1080,
							bytes: 4_000_000,
							codec: "av01.0.05M.08".into(),
						},
					)]),
					captions: BTreeMap::new(),
				}),
			},
		};
		let text = serde_json::to_string(&document).expect("serialise");
		assert_eq!(serde_json::from_str::<Document>(&text).expect("deserialise"), document);
		assert!(text.contains("\"type\":\"video\""));
		// A player is handed camelCase; the field is snake_case because Rust is.
		assert!(text.contains("\"frame_rate\":30.0"), "{text}");
		// Nothing says what a video lacks. An empty caption map writes nothing at all, and
		// there is no thumbhash key to be empty.
		assert!(!text.contains("captions"), "{text}");
		assert!(!text.contains("thumbhash"), "{text}");
	}

	/// One record copied verbatim out of `data/record/metadata.json` at version 3.
	///
	/// The migration's whole claim is that this loads without a transform, so the evidence is a
	/// real record rather than one written to fit. The full file -- 39 of these -- was loaded and
	/// re-serialised field for field before the split landed.
	const VERSION_THREE_RECORD: &str = r#"{
		"type": "image",
		"created": "2026-09-14T02:55:32.15685Z",
		"updated": "2026-09-14T02:55:32.15685Z",
		"blake3": "0e0624f079e617e53ed474ccd98a947b",
		"thumbhash": "+vcJBYCIh5iIh3ePhkeHcoiIj4f4",
		"source": {
			"mime": "image/png",
			"width": 1960,
			"height": 1274,
			"ratio": "20:13",
			"bytes": 477086
		},
		"metadata": { "color_space": "sRGB" },
		"variants": {
			"20805a43fdc2119f1aa8fae25c0ff8e1": {
				"mime": "image/avif",
				"width": 640,
				"height": 416,
				"quality": 0.68,
				"bytes": 2253
			}
		}
	}"#;

	#[test]
	fn a_version_three_record_loads_without_a_migration() {
		// The split into an envelope and a flattened body left every field where it was, which
		// is the only reason version 4 needs no transform. If this ever fails, `migrate` grows a
		// branch -- not a `#[serde(alias)]`, which would carry the old shape forever.
		let media: Media = serde_json::from_str(VERSION_THREE_RECORD).expect("a v3 record");
		let image = media.image().expect("a v3 record is a picture");
		assert_eq!(media.blake3, "0e0624f079e617e53ed474ccd98a947b");
		assert_eq!(image.thumbhash, "+vcJBYCIh5iIh3ePhkeHcoiIj4f4");
		assert_eq!(image.source.width, 1960);
		assert_eq!(image.variants.len(), 1);
		assert_eq!(media.kind(), "image");
	}

	#[test]
	fn a_version_three_record_survives_being_written_back() {
		// `cms image` rewrites every sidecar on the version bump, so what it writes has to be
		// the same document it read. Compared as JSON rather than as text: `type` is written
		// after `blake3` now that it comes from the flattened body, and key order is not
		// content.
		let media: Media = serde_json::from_str(VERSION_THREE_RECORD).expect("a v3 record");
		let written = serde_json::to_string(&media).expect("serialise");
		assert_eq!(
			serde_json::from_str::<serde_json::Value>(&written).expect("value"),
			serde_json::from_str::<serde_json::Value>(VERSION_THREE_RECORD).expect("value"),
		);
	}

	#[test]
	fn asking_a_video_for_a_picture_answers_nothing() {
		// The accessor is the whole guard: a caller that only makes sense for a picture cannot
		// reach a thumbhash through it, so a video is turned away at a visible line instead of
		// being served an empty string.
		let media = Media {
			created: "2026-09-14T00:00:00Z".into(),
			updated: "2026-09-14T00:00:00Z".into(),
			blake3: "aa11".into(),
			body: Body::Video(Video {
				source: VideoSource {
					mime: "video/mp4".into(),
					width: 1280,
					height: 720,
					ratio: "16:9".into(),
					bytes: 1,
					duration: 1.0,
					frame_rate: 30.0,
					frames: 30,
					audio: false,
					loudness: None,
					peak: None,
				},
				poster: "bb22".into(),
				variants: BTreeMap::new(),
				captions: BTreeMap::new(),
			}),
		};
		assert!(media.image().is_none());
		assert!(media.video().is_some());
		assert_eq!(media.kind(), "video");
	}
}
