/**
 * Read the visual layer out of the site's source, once, for the three gates that count it.
 *
 * Every rule in spec/architecture/css/ that rests on a number -- how many components apply a
 * recipe, how many frame declarations sit in StyleX, how many ramp values have no name -- needs
 * this same scan, and three copies of it would be three answers. It parses with svelte's own
 * compiler rather than matching the shape a declaration usually takes: spec/code.md, "Local code
 * does not hand-roll a standard". Whatever it cannot read comes back in `unreadable` and every
 * caller fails on it, because a scan that skips a block returns a number that is too small and
 * says nothing about having done so.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'svelte/compiler';

const SITE = fileURLToPath(new URL('..', import.meta.url));
export const ROOT = join(SITE, '../..');
/**
 * Every tree the visual layer is written in. It became two when the article renderer moved to
 * `libs/prose`: a gate that scans one of them reports a smaller corpus rather than a failure,
 * which is the way this kind of check goes quietly wrong.
 */
const SRC = [
	join(SITE, 'src'),
	join(SITE, '../../libs/prose/src'),
	join(SITE, '../../libs/tokens/src'),
];
const SCAN = relative(ROOT, fileURLToPath(import.meta.url));

/** The module every `stylex.create` call comes from, and the only one this scan recognises. */
const STYLEX = '@stylexjs/stylex';
/** Where the visual layer's named values live, and where its named groups do. */
const VOCABULARY = '@canmi/tokens/vocabulary.stylex';
const SURFACES = '@canmi/tokens/surfaces';
/** Where those two resolve to, so each module is spelled once. */
const LIB = 'libs/tokens/src';

/**
 * The two homes of a name, as paths. A gate counting application sites has to tell a read inside
 * the declaring module from one in a component, and the import specifier is not what `scan`
 * reports a file as.
 */
export const HOMES = {
	values: `${LIB}/vocabulary.stylex.ts`,
	groups: `${LIB}/surfaces.ts`,
};
/** Generated by paraglide on every build; nobody edits it and no rule here applies to it. */
const GENERATED = 'paraglide';

/** A value as the source writes it, which is the distinction all three gates turn on. */
export type Value =
	| { kind: 'literal'; raw: string }
	| { kind: 'named'; group: string; key: string }
	/** One property under several conditions. The merge unit is the property, so this is one. */
	| { kind: 'conditional'; branches: Value[] };

/** One property written inside one key of a `stylex.create` block. */
export type Declaration = {
	file: string;
	line: number;
	/** The key in the `create` object, which is the readable name StyleX stamps on the element. */
	block: string;
	/** The property as the source spells it, camelCase. */
	property: string;
	/** The `::before`-style selectors this declaration is nested under, outermost first. */
	within: string[];
	value: Value;
	/** Whether a `// unnamed:` note sits beside it -- spec/architecture/css/authoring.md. */
	marked: boolean;
};

/** One key of a `stylex.create` block, with whatever it spreads in. */
export type Block = {
	file: string;
	line: number;
	name: string;
	declarations: Declaration[];
	/** `...paper` and the like, by the name spread. */
	spreads: string[];
};

/** A `group.key` read somewhere in the source, which is what an application site looks like. */
export type Use = { file: string; line: number; group: string; key: string };

/** A file, or a construct inside one, this scan could not read. Every gate fails on these. */
export type Unreadable = { file: string; line: number; what: string };

/** A name the visual layer declares: `surfaces`, or one of the vocabulary's const groups. */
export type Group = { file: string; name: string; keys: { key: string; line: number }[] };

export type Scan = {
	blocks: Block[];
	/** Every `X.Y` where `X` was imported from the vocabulary or the surfaces module. */
	uses: Use[];
	/** Every group `stylex.create` or `stylex.defineConsts` declares, wherever it is declared. */
	groups: Group[];
	unreadable: Unreadable[];
	/** How many files were opened, so a scan that found nothing can say whether it looked. */
	files: number;
};

type Node = { type: string; start: number; end: number; [key: string]: unknown };
type Comment = { type: string; value: string; start: number; end: number };

function isNode(value: unknown): value is Node {
	return typeof value === 'object' && value !== null && typeof (value as Node).type === 'string';
}

/** Every descendant of `node`, including it. */
function* walk(node: Node): Generator<Node> {
	yield node;
	for (const value of Object.values(node)) {
		if (Array.isArray(value)) {
			for (const item of value) if (isNode(item)) yield* walk(item);
		} else if (isNode(value)) yield* walk(value);
	}
}

/** Every `.svelte` and `.ts` file under `src`: everywhere a StyleX block can be written. */
function sources(dir: string): string[] {
	const found: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		if (entry.name === GENERATED) continue;
		const path = join(dir, entry.name);
		if (entry.isDirectory()) found.push(...sources(path));
		else if (/\.(svelte|ts)$/.test(entry.name)) found.push(path);
	}
	return found;
}

/**
 * A `.ts` file reaches the same parser inside a script tag rather than a second parser of its own.
 *
 * TypeScript 7 publishes no `createSourceFile`, and two readers of one language is the
 * disagreement spec/code.md names. The wrapper's length is what every offset is shifted by.
 */
const WRAPPER = '<script lang="ts">';

type Parsed = { scripts: Node[]; fragment: Node; comments: Comment[]; shift: number };

function read(path: string, source: string): Parsed {
	const svelte = path.endsWith('.svelte');
	const root = parse(svelte ? source : WRAPPER + source + '</script>', { modern: true });
	const scripts: Node[] = [];
	for (const script of [root.module, root.instance]) {
		if (script !== null && script !== undefined) scripts.push(script.content as unknown as Node);
	}
	return {
		scripts,
		fragment: root.fragment as unknown as Node,
		comments: root.comments as unknown as Comment[],
		shift: svelte ? 0 : WRAPPER.length,
	};
}

/** The 1-based line an offset falls on, counted in the file rather than in the parsed text. */
function liner(source: string, shift: number): (offset: number) => number {
	const breaks: number[] = [];
	for (let index = 0; index < source.length; index += 1) {
		if (source[index] === '\n') breaks.push(index);
	}
	return (offset) => {
		const at = offset - shift;
		let line = 1;
		for (const brk of breaks) {
			if (brk >= at) break;
			line += 1;
		}
		return line;
	};
}

/** The name a file binds `@stylexjs/stylex` to; a default or named import is not one this reads. */
function namespaceOf(program: Node, note: (node: Node, what: string) => void): string | undefined {
	let name: string | undefined;
	for (const node of walk(program)) {
		if (node.type !== 'ImportDeclaration') continue;
		const from = node['source'];
		if (!isNode(from) || from['value'] !== STYLEX) continue;
		for (const raw of node['specifiers'] as unknown[]) {
			if (!isNode(raw)) continue;
			const local = raw['local'];
			const bound = isNode(local) ? local['name'] : undefined;
			if (typeof bound !== 'string') continue;
			if (raw.type === 'ImportNamespaceSpecifier') name = bound;
			else note(raw, `binds ${STYLEX} as '${bound}' rather than as a namespace`);
		}
	}
	return name;
}

/** Local name to exported name, for the two modules that hold the visual layer's names. */
function bindingsOf(program: Node): Map<string, string> {
	const bound = new Map<string, string>();
	for (const node of walk(program)) {
		if (node.type !== 'ImportDeclaration') continue;
		const from = node['source'];
		if (!isNode(from)) continue;
		if (from['value'] !== VOCABULARY && from['value'] !== SURFACES) continue;
		for (const raw of node['specifiers'] as unknown[]) {
			if (!isNode(raw) || raw.type !== 'ImportSpecifier') continue;
			const local = raw['local'];
			const imported = raw['imported'];
			if (!isNode(local) || !isNode(imported)) continue;
			const alias = local['name'];
			const exported = imported['name'];
			if (typeof alias === 'string' && typeof exported === 'string') bound.set(alias, exported);
		}
	}
	return bound;
}

/** The property or key a `Property` node names, or undefined where it is computed. */
function keyOf(node: Node): string | undefined {
	if (node['computed'] === true) return undefined;
	const key = node['key'];
	if (!isNode(key)) return undefined;
	if (typeof key['name'] === 'string') return key['name'];
	if (typeof key['value'] === 'string') return key['value'];
	return undefined;
}

/** The StyleX entry point `node` calls, where it is one written on the imported namespace. */
function stylexCall(node: Node, namespace: string): string | undefined {
	if (node.type !== 'CallExpression') return undefined;
	const callee = node['callee'];
	if (!isNode(callee) || callee.type !== 'MemberExpression' || callee['computed'] === true) {
		return undefined;
	}
	const object = callee['object'];
	const property = callee['property'];
	if (!isNode(object) || !isNode(property) || object['name'] !== namespace) return undefined;
	return typeof property['name'] === 'string' ? property['name'] : undefined;
}

/** The single object literal a StyleX entry point was handed, or undefined where it was not one. */
function soleObject(node: Node): Node | undefined {
	const args = node['arguments'] as unknown[];
	const [only] = args;
	if (args.length !== 1 || !isNode(only) || only.type !== 'ObjectExpression') return undefined;
	return only;
}

type Reading = {
	file: string;
	line: (offset: number) => number;
	comments: Comment[];
	note: (node: Node, what: string) => void;
	scripts: Node[];
};

export function scan(): Scan {
	const blocks: Block[] = [];
	const uses: Use[] = [];
	const groups: Group[] = [];
	const unreadable: Unreadable[] = [];
	const paths = SRC.flatMap((tree) => sources(tree));

	for (const path of paths) {
		const file = relative(ROOT, path);
		const source = readFileSync(path, 'utf8');
		if (!source.includes(STYLEX) && !source.includes(SURFACES)) continue;
		let parsed: Parsed;
		try {
			parsed = read(path, source);
		} catch (error) {
			const why = error instanceof Error ? error.message : String(error);
			unreadable.push({ file, line: 1, what: `does not parse: ${why}` });
			continue;
		}
		const line = liner(source, parsed.shift);
		const note = (node: Node, what: string) =>
			unreadable.push({ file, line: line(node.start), what });
		const ctx: Reading = { file, line, comments: parsed.comments, note, scripts: parsed.scripts };

		// Imports are read from the scripts; uses and `create` calls from the scripts and the
		// markup both, because a surface reaches an element from inside a class attribute.
		let namespace: string | undefined;
		const named = new Map<string, string>();
		for (const program of parsed.scripts) {
			namespace = namespaceOf(program, note) ?? namespace;
			for (const [local, exported] of bindingsOf(program)) named.set(local, exported);
		}

		for (const program of [...parsed.scripts, parsed.fragment]) {
			for (const node of walk(program)) {
				if (node.type === 'MemberExpression' && node['computed'] !== true) {
					const object = node['object'];
					const property = node['property'];
					const group = isNode(object) ? named.get(String(object['name'])) : undefined;
					const key = isNode(property) ? property['name'] : undefined;
					if (group !== undefined && typeof key === 'string') {
						uses.push({ file, line: line(node.start), group, key });
					}
				}
				if (namespace === undefined) continue;
				if (node.type === 'VariableDeclarator') {
					const group = readGroup(node, namespace, ctx);
					if (group !== undefined) groups.push(group);
					continue;
				}
				const method = stylexCall(node, namespace);
				if (method !== 'create') continue;
				const only = soleObject(node);
				if (only === undefined) {
					note(node, 'is a `stylex.create` call whose argument is not one object literal');
					continue;
				}
				blocks.push(...readCreate(only, ctx));
			}
		}
	}

	// `text.length` reads a local string in a file that also imports the `text` ladder, and no
	// scope analysis separates the two. Keeping only the keys a group actually declares does,
	// and a misspelled key is not lost with them: it is a `var()` nothing declares, which
	// `vocabulary.stylex.ts` records as tsc's to catch.
	const declared = new Map<string, Set<string>>();
	for (const group of groups) {
		declared.set(group.name, new Set(group.keys.map((each) => each.key)));
	}
	const real = uses.filter((use) => declared.get(use.group)?.has(use.key) === true);

	return { blocks, uses: real, groups, unreadable, files: paths.length };
}

/**
 * The name a declarator gives a group of styles or constants, with the keys under it.
 *
 * Both entry points are read: `surfaces.ts` writes `create` and the vocabulary writes
 * `defineConsts`, and the threshold in extraction.md counts application sites for either.
 */
function readGroup(node: Node, namespace: string, ctx: Reading): Group | undefined {
	const id = node['id'];
	const init = node['init'];
	if (!isNode(id) || typeof id['name'] !== 'string' || !isNode(init)) return undefined;
	const method = stylexCall(init, namespace);
	if (method !== 'create' && method !== 'defineConsts') return undefined;
	const only = soleObject(init);
	if (only === undefined) {
		ctx.note(init, `declares '${id['name']}' from an argument that is not one object literal`);
		return undefined;
	}
	const keys: { key: string; line: number }[] = [];
	for (const raw of only['properties'] as unknown[]) {
		if (!isNode(raw)) continue;
		const key = raw.type === 'Property' ? keyOf(raw) : undefined;
		if (key === undefined) {
			ctx.note(raw, `is a key of '${id['name']}' this scan cannot name`);
			continue;
		}
		keys.push({ key, line: ctx.line(raw.start) });
	}
	return { file: ctx.file, name: id['name'], keys };
}

/** The keys of one `stylex.create` object, each with the declarations written under it. */
function readCreate(object: Node, ctx: Reading): Block[] {
	const found: Block[] = [];
	for (const raw of object['properties'] as unknown[]) {
		if (!isNode(raw)) continue;
		if (raw.type !== 'Property') {
			ctx.note(raw, 'is a `stylex.create` entry this scan cannot read as a key');
			continue;
		}
		const name = keyOf(raw);
		const value = raw['value'];
		if (name === undefined || !isNode(value)) {
			ctx.note(raw, 'is a `stylex.create` key this scan cannot name');
			continue;
		}
		const body = resolve(value, ctx);
		if (body === undefined) {
			ctx.note(raw, `is the key '${name}', whose value is no object literal this scan can read`);
			continue;
		}
		const block: Block = {
			file: ctx.file,
			line: ctx.line(body.start),
			name,
			declarations: [],
			spreads: [],
		};
		readStyle(block, body, [], ctx);
		found.push(block);
	}
	return found;
}

/**
 * The object literal behind a value, following a name declared in the same file.
 *
 * `surfaces.ts` writes `paper` as a `const` and then spreads it, so the shorthand key `paper,`
 * is an identifier where every other key is an object literal.
 */
function resolve(value: Node, ctx: Reading): Node | undefined {
	if (value.type === 'ObjectExpression') return value;
	if (value.type !== 'Identifier' || typeof value['name'] !== 'string') return undefined;
	const wanted = value['name'];
	for (const program of ctx.scripts) {
		for (const node of walk(program)) {
			if (node.type !== 'VariableDeclarator') continue;
			const id = node['id'];
			const init = node['init'];
			if (!isNode(id) || id['name'] !== wanted) continue;
			if (isNode(init) && init.type === 'ObjectExpression') return init;
		}
	}
	return undefined;
}

/** Whether a key inside a style object selects something rather than naming a property. */
function isSelector(key: string): boolean {
	return key.startsWith(':') || key.startsWith('@');
}

/** One style object's declarations, descending through the selectors nested inside it. */
function readStyle(block: Block, object: Node, within: string[], ctx: Reading): void {
	for (const raw of object['properties'] as unknown[]) {
		if (!isNode(raw)) continue;
		if (raw.type === 'SpreadElement') {
			const argument = raw['argument'];
			const spread = isNode(argument) ? argument['name'] : undefined;
			if (typeof spread === 'string') block.spreads.push(spread);
			else ctx.note(raw, `spreads something this scan cannot name into the key '${block.name}'`);
			continue;
		}
		if (raw.type !== 'Property') {
			ctx.note(raw, `is an entry of the key '${block.name}' this scan cannot read`);
			continue;
		}
		const property = keyOf(raw);
		const value = raw['value'];
		if (property === undefined || !isNode(value)) {
			ctx.note(raw, `is a declaration in the key '${block.name}' this scan cannot name`);
			continue;
		}
		if (isSelector(property)) {
			const nested = resolve(value, ctx);
			if (nested === undefined) {
				ctx.note(raw, `selects '${property}' in the key '${block.name}' with no object under it`);
				continue;
			}
			readStyle(block, nested, [...within, property], ctx);
			continue;
		}
		const written = valueOf(value, ctx, `${block.name}.${property}`);
		if (written === undefined) continue;
		block.declarations.push({
			file: ctx.file,
			line: ctx.line(raw.start),
			block: block.name,
			property,
			within,
			value: written,
			marked: markedAt(raw, ctx),
		});
	}
}

/** Whether a `// unnamed:` note sits on the declaration's own line or the line above it. */
function markedAt(node: Node, ctx: Reading): boolean {
	const line = ctx.line(node.start);
	for (const comment of ctx.comments) {
		if (!comment.value.trim().startsWith('unnamed:')) continue;
		const at = ctx.line(comment.start);
		if (at === line || at === line - 1) return true;
	}
	return false;
}

/** What one declaration's value is: a literal, a name from the vocabulary, or one per condition. */
function valueOf(node: Node, ctx: Reading, where: string): Value | undefined {
	if (node.type === 'Literal') {
		return { kind: 'literal', raw: String(node['raw'] ?? node['value']) };
	}
	if (node.type === 'UnaryExpression' && node['operator'] === '-') {
		const argument = node['argument'];
		if (isNode(argument) && argument.type === 'Literal') {
			return { kind: 'literal', raw: `-${String(argument['raw'] ?? argument['value'])}` };
		}
	}
	if (node.type === 'MemberExpression' && node['computed'] !== true) {
		const object = node['object'];
		const property = node['property'];
		const group = isNode(object) ? object['name'] : undefined;
		const key = isNode(property) ? property['name'] : undefined;
		if (typeof group === 'string' && typeof key === 'string') {
			return { kind: 'named', group, key };
		}
	}
	if (node.type === 'ObjectExpression') {
		const branches: Value[] = [];
		for (const raw of node['properties'] as unknown[]) {
			if (!isNode(raw) || raw.type !== 'Property') {
				ctx.note(node, `is a condition of '${where}' this scan cannot read`);
				return undefined;
			}
			const value = raw['value'];
			if (!isNode(value)) {
				ctx.note(raw, `is a condition of '${where}' whose value this scan cannot read`);
				return undefined;
			}
			const branch = valueOf(value, ctx, where);
			if (branch === undefined) return undefined;
			branches.push(branch);
		}
		return { kind: 'conditional', branches };
	}
	ctx.note(node, `is the value of '${where}', written as a ${node.type} this scan cannot read`);
	return undefined;
}

/** Every literal a value carries, flattening the conditions a property may be written under. */
export function literals(value: Value): string[] {
	if (value.kind === 'literal') return [value.raw];
	if (value.kind === 'named') return [];
	return value.branches.flatMap(literals);
}

/** What a gate prints when its scan could not read part of its input. See spec/code.md. */
export function untrusted(found: Unreadable[]): string[] {
	return found.map(
		(each) =>
			`${each.file}:${each.line} ${each.what}. This scan is measuring less than the tree ` +
			`holds, so its count is not a measurement. Fix the scan in ${SCAN} before trusting it.`,
	);
}
