# See spec/architecture/firewall.md.

[[rules]]
name = "Pass Probe"
phase = "http_request_firewall_custom"
action = "skip"
skip_phases = ["http_ratelimit"]
expression = "../all/pass-probe.txt"

[[rules]]
name = "Block Probes"
phase = "http_request_firewall_custom"
action = "block"
expression = "../all/block-probes.txt"

[[rules]]
name = "Rate Cap"
phase = "http_ratelimit"
action = "block"
expression = "rate-cap.txt"
characteristics = ["cf.colo.id", "ip.src"]
period = 10
requests_per_period = 50
mitigation_timeout = 10
